package com.TestInterfaceDevelopMapper.mapper;

import com.TestInterfaceDevelopMapper.model.User;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper //标识为mybatis数据层接口
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     */
    List<User> getAllUser(User user);

    int login(User user);
    int addUser(User user);
    int updateUserInfo(User user);
    int deleteUser(Integer userId);
    void delPrimaryKeyField();
    void reAddPrimaryKeyField();
}
